apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-demo
  namespace: coohua-test
spec:
  template:
    metadata:
      labels:
        app: jenkins-demo
    spec:
      imagePullSecrets:
      - name: coohua-registry
      containers:
      - image: registry.cn-qingdao.aliyuncs.com/coohua_img/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo
        env:
        - name: branch
          value: <BRANCH_NAME>
